# Generated by Django 4.2.7 on 2023-11-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0, help_text='It will be used to sort skills.', verbose_name='Order'),
        ),
    ]
