# Generated by Django 4.2.7 on 2023-11-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_skill_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
