# Generated by Django 4.2.7 on 2023-11-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_document_options_remove_document_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='show_on_page',
            field=models.BooleanField(default=True, verbose_name='Show On Menu'),
        ),
    ]
