# Generated by Django 4.2.7 on 2023-12-04 08:19

from django.db import migrations, models
import resume_app.custom_storages


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_document_show_on_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, default='', storage=resume_app.custom_storages.DocumentStorage(), upload_to='', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='file',
            field=models.ImageField(blank=True, default='', null=True, storage=resume_app.custom_storages.ImageSettingStorage(), upload_to='', verbose_name='Image'),
        ),
    ]
