# Generated by Django 4.2.7 on 2023-11-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0002_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='End Date'),
        ),
    ]
