# Generated by Django 4.2.7 on 2023-11-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0003_alter_experience_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('school_name', models.CharField(blank=True, default='', max_length=255, verbose_name='School Name')),
                ('faculty', models.CharField(blank=True, default='', max_length=255, verbose_name='Faculty')),
                ('department', models.CharField(blank=True, default='', max_length=255, verbose_name='Department')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=None, null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ('-start_date',),
            },
        ),
    ]
