# Generated by Django 4.2.7 on 2023-11-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0004_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order', models.IntegerField(default=0, help_text='It will be used to sort social media.', verbose_name='Order')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('url', models.CharField(blank=True, default='', max_length=255, verbose_name='URL')),
                ('icon', models.CharField(blank=True, default='', max_length=255, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
                'ordering': ('order',),
            },
        ),
    ]
