# Generated by Django 4.2.7 on 2023-11-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0005_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='URL'),
        ),
    ]
